# Generated by Django 2.0.5 on 2018-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age_distribution_10', models.IntegerField()),
                ('age_distribution_20', models.IntegerField()),
                ('age_distribution_30', models.IntegerField()),
                ('age_distribution_50', models.IntegerField()),
                ('age_distribution_70', models.IntegerField()),
                ('age_distribution_71', models.IntegerField()),
                ('total_bearing_name', models.IntegerField()),
                ('average_age', models.IntegerField()),
                ('number_of_letters', models.CharField(max_length=16)),
                ('double_name', models.BooleanField()),
                ('frequency', models.CharField(max_length=128)),
                ('meaning', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('domain', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GirlName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age_distribution_10', models.IntegerField()),
                ('age_distribution_20', models.IntegerField()),
                ('age_distribution_30', models.IntegerField()),
                ('age_distribution_50', models.IntegerField()),
                ('age_distribution_70', models.IntegerField()),
                ('age_distribution_71', models.IntegerField()),
                ('total_bearing_name', models.IntegerField()),
                ('average_age', models.IntegerField()),
                ('number_of_letters', models.CharField(max_length=16)),
                ('double_name', models.BooleanField()),
                ('frequency', models.CharField(max_length=128)),
                ('meaning', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PopularName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=256)),
                ('variants', models.TextField()),
            ],
        ),
    ]
