# Generated by Django 2.0.5 on 2018-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyname',
            name='variants',
            field=models.ManyToManyField(related_name='boy_names', to='api.Variant'),
        ),
        migrations.AddField(
            model_name='girlname',
            name='variants',
            field=models.ManyToManyField(related_name='girl_names', to='api.Variant'),
        ),
        migrations.AlterField(
            model_name='boyname',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='girlname',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='language',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='variants',
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('language', 'name')},
        ),
    ]
