# Generated by Django 2.0.5 on 2018-06-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180611_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='popularname',
            unique_together={('year', 'position')},
        ),
    ]
