# Generated by Django 2.0.5 on 2018-06-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_footertexts'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE `api_boyname` CHANGE `name` `name` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;'),
        migrations.RunSQL('ALTER TABLE `api_girlname` CHANGE `name` `name` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;'),
        migrations.RunSQL('ALTER TABLE `api_variant` CHANGE `name` `name` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;'),
    ]
