# Generated by Django 2.0.5 on 2018-06-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180612_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertexts',
            options={'verbose_name_plural': 'footer text'},
        ),
        migrations.RemoveField(
            model_name='footertexts',
            name='text',
        ),
    ]
