# Generated by Django 2.0.5 on 2018-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180622_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertexts',
            name='boy_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footertexts',
            name='girl_names',
            field=models.TextField(null=True),
        ),
    ]
